spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${LOCAL_URL_DB}:5432/vibe_credenciais
    username: admin
    password: vibe_password

jwt:
  secret: 4Z^XrroxR@dWxqf$mTTKwW$!@#qGr4P


